name: Build iOS DEB (Fixed)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. 彻底重新安装 Theos（确保路径和文件完整）
      - name: Install Theos Completely
        run: |
          # 先删除可能残留的旧 Theos
          sudo rm -rf ~/theos
          # 重新克隆完整 Theos（含子模块）
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # 下载并解压 iOS 15.0 SDK（稳定版本，链接可靠）
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS15.0.sdk.tar.xz
          tar -xJf iPhoneOS15.0.sdk.tar.xz -C ~/theos/sdks  # 用 -xJf 适配 .tar.xz 格式

      # 2. 安装所有必需依赖（包括签名工具）
      - name: Install All Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ldid dpkg-dev fakeroot build-essential

      # 3. 自动找到项目根目录（不用你手动改路径）
      - name: Find Project Root
        id: find_root
        run: |
          # 自动找包含 Makefile 的目录（你的 Tweak 项目根目录）
          PROJECT_ROOT=$(find . -name "Makefile" -type f | head -1 | xargs dirname)
          echo "PROJECT_ROOT=$PROJECT_ROOT" >> $GITHUB_OUTPUT

      # 4. 编译并打包 DEB（用自动找到的路径）
      - name: Build DEB Package
        run: |
          export THEOS=~/theos
          cd ${{ steps.find_root.outputs.PROJECT_ROOT }}
          # 强制 64 位编译，适配所有现代 iOS 设备
          make package THEOS_DEVICE_IP=localhost ARCH=arm64 -j4

      # 5. 自动上传 DEB（不管你放哪都能找到）
      - name: Upload DEB File
        uses: actions/upload-artifact@v4
        with:
          name: My-iOS-Deb
          path: ${{ steps.find_root.outputs.PROJECT_ROOT }}/packages/*.deb
