name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install make git ldid xz
          # 确保Xcode命令行工具正确安装
          xcode-select --install || true
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          
      - name: Prepare Theos environment
        run: |
          # 清理旧的Theos目录
          rm -rf "$GITHUB_WORKSPACE/theos"
          
          # 克隆Theos仓库
          git clone https://github.com/LexusLs300h/theos.git "$GITHUB_WORKSPACE/theos"
          cd "$GITHUB_WORKSPACE/theos"
          git submodule update --init --recursive
          
          # 验证Theos核心文件
          if [ ! -f "$GITHUB_WORKSPACE/theos/makefiles/master.mk" ]; then
            echo "Error: Theos directory is invalid, master.mk not found!"
            ls -la "$GITHUB_WORKSPACE/theos/makefiles"
            exit 1
          fi
          
          # 下载并安装iOS SDK（关键步骤）
          SDK_VERSION="16.5"
          SDK_DIR="$GITHUB_WORKSPACE/theos/sdks"
          mkdir -p "$SDK_DIR"
          
          # 从Theos官方SDK仓库下载
          curl -L "https://github.com/theos/sdks/archive/refs/tags/$SDK_VERSION.tar.gz" -o "$SDK_DIR/sdk.tar.gz"
          
          # 解压SDK
          tar -zxf "$SDK_DIR/sdk.tar.gz" -C "$SDK_DIR"
          mv "$SDK_DIR/sdks-$SDK_VERSION/iPhoneOS$SDK_VERSION.sdk" "$SDK_DIR/"
          rm -rf "$SDK_DIR/sdks-$SDK_VERSION" "$SDK_DIR/sdk.tar.gz"
          
          # 验证SDK是否安装成功
          if [ ! -d "$SDK_DIR/iPhoneOS$SDK_VERSION.sdk" ]; then
            echo "Error: iOS SDK $SDK_VERSION not found!"
            ls -la "$SDK_DIR"
            exit 1
          fi
          
          echo "Theos and iOS SDK $SDK_VERSION prepared successfully"
          
      - name: Build Tweak
        run: |
          export THEOS="$GITHUB_WORKSPACE/theos"
          export SDKVERSION=16.5
          export SYSROOT="$THEOS/sdks/iPhoneOS16.5.sdk"
          
          # 打印环境变量用于调试
          echo "THEOS path: $THEOS"
          echo "SDK path: $SYSROOT"
          
          # 执行构建
          make clean
          make package SCHEME=rootless
          
      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
