name: Build iOS DEB Package

on:
  push:
    branches: [ main ]  # 监听 main 分支的推送事件
  pull_request:
    branches: [ main ]  # 监听 main 分支的 PR 事件

jobs:
  build:
    runs-on: macos-latest 

    steps:
      # 1. 检出代码到工作目录
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. 安装 Theos 开发环境（iOS 越狱开发工具链）
      

      # 3. 安装编译依赖（如 ldid 用于签名）
      - name: Install dependencies
        run: |
          brew update
          brew install make git ldid xz
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Verify existing Theos directory
      # 4. 编译并打包 DEB
      - name: Build DEB
        run: |
          export THEOS=~/theos
          # 进入项目目录（根据实际结构调整路径）
          cd ./your_tweak_project
          # 执行 Theos 编译命令（ARCH=arm64 适配 64 位设备）
          make package THEOS_DEVICE_IP=localhost THEOS_DEVICE_PORT=22 ARCH=arm64

      # 5. 上传 DEB 包作为构建产物
      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-deb-package
          path: ./your_tweak_project/packages/*.deb  # DEB 包输出路径
