name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install make git ldid xz
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Verify existing Theos directory
        run: |
          # 强制删除Theos目录
          rm -rf "/Users/runner/work/WeChatRedEnvelop/WeChatRedEnvelop/theos"
          # 克隆Theos并同步子模块
          git clone --recursive https://github.com/LexusLs300h/theos.git "/Users/runner/work/WeChatRedEnvelop/WeChatRedEnvelop/theos"
          # 验证关键文件是否存在
          if [ ! -f "/Users/runner/work/WeChatRedEnvelop/WeChatRedEnvelop/theos/makefiles/master.mk" ]; then
            echo "Error: Theos directory is invalid, master.mk not found!"
            exit 1
          fi
      - name: Build Tweak using existing Theos
        run: |
          # 直接指定已存在的Theos目录路径
          export THEOS=/Users/runner/work/WeChatRedEnvelop/WeChatRedEnvelop/theos
          make package
      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
