name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          DEPS=(make git ldid xz curl wget)
          UNINSTALLED=()
          for dep in "${DEPS[@]}"; do
            brew list "$dep" &>/dev/null || UNINSTALLED+=("$dep")
          done
          [ ${#UNINSTALLED[@]} -gt 0 ] && brew install "${UNINSTALLED[@]}" || echo "All dependencies installed."
          xcode-select --install || true
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Setup Theos & SDK
        run: |
          rm -rf "$GITHUB_WORKSPACE/theos"
          git clone --depth 1 https://github.com/LexusLs300h/theos.git "$GITHUB_WORKSPACE/theos"
          cd "$GITHUB_WORKSPACE/theos" && git submodule update --init --recursive
          [ ! -f "makefiles/master.mk" ] && { echo "Theos invalid!"; exit 1; }

          SDK_VER="16.5"
          SDK_DIR="$GITHUB_WORKSPACE/theos/sdks"
          mkdir -p "$SDK_DIR"
          SDK_TEMP="$SDK_DIR/sdk.tar.gz"
          SDK_URLS=(
            "https://github.com/LexusLs300h/sdks/archive/refs/tags/16.5.tar.gz"
            "https://example.com/backup/sdk/16.5.tar.gz"
          )

          for url in "${SDK_URLS[@]}"; do
            curl -fL --retry 5 --connect-timeout 15 --output "$SDK_TEMP" "$url" && break
          done
          [ ! -f "$SDK_TEMP" ] && { echo "SDK download failed!"; exit 1; }

          [ $(stat -f%z "$SDK_TEMP") -lt $((100 * 1024 * 1024)) ] && { echo "SDK corrupted!"; rm "$SDK_TEMP"; exit 1; }

          mkdir -p "$SDK_DIR/temp"
          file "$SDK_TEMP" | grep -q "gzip" && tar -zxf "$SDK_TEMP" -C "$SDK_DIR/temp"
          file "$SDK_TEMP" | grep -q "XZ" && tar -Jxf "$SDK_TEMP" -C "$SDK_DIR/temp"
          [ $? -ne 0 ] && { echo "Unsupported archive!"; exit 1; }

          SDK_SRC=$(find "$SDK_DIR/temp" -name "iPhoneOS$SDK_VER.sdk" -type d -print -quit)
          [ -z "$SDK_SRC" ] && { echo "SDK not found in extract!"; exit 1; }

          mv "$SDK_SRC" "$SDK_DIR/" && rm -rf "$SDK_DIR/temp" "$SDK_TEMP"
          FINAL_SDK="$SDK_DIR/iPhoneOS$SDK_VER.sdk"
          [ ! -d "$FINAL_SDK" ] && { echo "SDK path invalid!"; exit 1; }
          [ ! -f "$FINAL_SDK/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h" ] && { echo "Missing header!"; exit 1; }
          echo "SDK installed: $FINAL_SDK"

      - name: Build Tweak
        run: |
          export THEOS="$GITHUB_WORKSPACE/theos"
          export SDKVERSION=16.5
          export SYSROOT="$THEOS/sdks/iPhoneOS16.5.sdk"
          [ ! -d "$SYSROOT" ] && { echo "SYSROOT invalid!"; exit 1; }
          make clean && make package SCHEME=rootless

      - uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
